rework ci path filters (#12)
* rework ci path filters

* run enforce-license-compliance on pushes as well

diff --git a/.github/workflows/api-ci.yml b/.github/workflows/api-ci.yml
--- a/.github/workflows/api-ci.yml
+++ b/.github/workflows/api-ci.yml
@@ -1,26 +1,11 @@
 name: API CI
 
 on:
-  push:
-    tags:
-      - prod-*
-    branches:
-      - main
-      - staging
-    paths:
-      - 'apps/codecov-api/**'
-      - 'apps/codecov-api'
-      - 'libs/**'
-  pull_request:
-    paths:
-      - 'apps/codecov-api/**'
-      - 'apps/codecov-api'
-      - 'libs/**'
-  merge_group:
-    paths:
-      - 'apps/codecov-api/**'
-      - 'apps/codecov-api'
-      - 'libs/**'
+  workflow_call:
+    inputs: 
+      skip:
+        type: boolean
+        default: false
 
 permissions:
   contents: "read"
@@ -28,25 +13,24 @@ permissions:
   issues: "write"
   pull-requests: "write"
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
-  cancel-in-progress: true
-
 jobs:
   api-lint:
     name: Run Lint (API)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/lint.yml@v1.2.31
     with:
       working_directory: apps/codecov-api
 
   api-mypy:
     name: Patch typing (API)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/mypy.yml@v1.2.31
     with:
       working_directory: apps/codecov-api
 
   api-build:
     name: Build App (API)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/build-app.yml@v1.2.31
     secrets: inherit
     with:
@@ -56,6 +40,7 @@ jobs:
   # Runs create-commit, create-report
   api-codecovstartup:
     name: Codecov Startup (API)
+    if: ${{ inputs.skip == false }}
     needs: api-build
     uses: codecov/gha-workflows/.github/workflows/codecov-startup.yml@v1.2.31
     secrets: inherit
@@ -64,8 +49,9 @@ jobs:
 
   api-test:
     name: Test (API)
+    if: ${{ inputs.skip == false }}
     needs: [api-build, api-codecovstartup]
-    uses: codecov/gha-workflows/.github/workflows/run-tests-split.yml@v1.2.31
+    uses: codecov/gha-workflows/.github/workflows/run-tests-split.yml@pr45
     secrets: inherit
     with:
       run_integration: false
@@ -75,6 +61,7 @@ jobs:
 
   api-build-self-hosted:
     name: Build Self Hosted (API)
+    if: ${{ inputs.skip == false }}
     needs: [api-build, api-test]
     uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.31
     secrets: inherit
@@ -85,7 +72,7 @@ jobs:
   api-staging:
     name: Push Staging Image (API)
     needs: [api-build, api-test]
-    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/staging' && github.repository_owner == 'codecov' }}
+    if: ${{ inputs.skip == false && github.event_name == 'push' && github.event.ref == 'refs/heads/staging' && github.repository_owner == 'codecov' }}
     uses: codecov/gha-workflows/.github/workflows/push-env.yml@v1.2.31
     secrets: inherit
     with:
@@ -97,7 +84,7 @@ jobs:
   api-production:
     name: Push Production Image (API)
     needs: [api-build, api-test]
-    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
+    if: ${{ inputs.skip == false && github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
     uses: codecov/gha-workflows/.github/workflows/push-env.yml@v1.2.31
     secrets: inherit
     with:
@@ -110,9 +97,34 @@ jobs:
     name: Push Self Hosted Image (API)
     needs: [api-build-self-hosted, api-test]
     secrets: inherit
-    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
+    if: ${{ inputs.skip == false && github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
     uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.31
     with:
       push_rolling: true
       repo: ${{ vars.CODECOV_API_IMAGE_V2 || 'codecov/self-hosted-api' }}
       working_directory: apps/codecov-api
+
+  # This job works around a strange interaction between reusable workflows and
+  # path filters.
+  #
+  # When a job that uses a reusable workflow is skipped, a single check shows up
+  # for it (e.g. `API CI / Test`). If the job is _not_ skipped, that check does
+  # not appear and instead you see checks for all of the jobs nested in the
+  # reusable workflow (`API CI / Test / Run tests`). There's no single check
+  # that's consistently there which you can mark as required.
+  #
+  # Because this job does not use a reusable workflow, it will produce the same
+  # check whether or not it is skipped. So, we can make this check required and
+  # have it figure out whether the jobs we actually care about failed.
+  api-required-checks:
+    name: Required checks (API)
+    if: ${{ !cancelled() && inputs.skip == false }}
+    runs-on: ubuntu-latest
+    needs: [api-test, api-lint]
+    steps:
+      - name: Fail lint
+        if: ${{ needs.api-lint.result == 'failure' }}
+        run: exit 1
+      - name: Fail tests
+        if: ${{ needs.api-test.outputs.tests_passed == 'failure' }}
+        run: exit 1
diff --git a/.github/workflows/shared-ci.yml b/.github/workflows/shared-ci.yml
--- a/.github/workflows/shared-ci.yml
+++ b/.github/workflows/shared-ci.yml
@@ -1,35 +1,24 @@
 name: Shared CI
 
 on:
-  push:
-    branches:
-      - main
-    paths:
-      - 'libs/shared/**'
-      - 'libs/shared'
-  pull_request:
-    paths:
-      - 'libs/shared/**'
-      - 'libs/shared'
-  merge_group:
-    paths:
-      - 'libs/shared/**'
-      - 'libs/shared'
-
-concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
-  cancel-in-progress: true
+  workflow_call:
+    inputs: 
+      skip:
+        type: boolean
+        default: false
 
 jobs:
   # TODO: get mypy running
   shared-lint:
     name: Run Lint (Shared)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/lint.yml@v1.2.31
     with:
       working_directory: libs/shared
 
   shared-codecovstartup:
     name: Codecov Startup (Shared)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/codecov-startup.yml@v1.2.31
     secrets: inherit
     with:
@@ -37,6 +26,7 @@ jobs:
 
   shared-test:
     name: Test (Shared)
+    if: ${{ inputs.skip == false }}
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -62,17 +52,18 @@ jobs:
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
-          name: coveragefiles
+          name: shared-coveragefiles
           path: libs/shared/tests/*.coverage.xml
 
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
-          name: junitfiles
+          name: shared-junitfiles
           path: libs/shared/tests/*junit*.xml
 
   shared-upload-to-codecov:
     name: Upload to Codecov (shared)
+    if: ${{ inputs.skip == false }}
     needs: [shared-test]
     runs-on: ubuntu-latest
     strategy:
@@ -102,13 +93,13 @@ jobs:
         id: download_coverage
         uses: actions/download-artifact@v4
         with:
-          name: coveragefiles
+          name: shared-coveragefiles
 
       - name: Download test results
         id: download_test_results
         uses: actions/download-artifact@v4
         with:
-          name: junitfiles
+          name: shared-junitfiles
 
       - name: Uploading unit test coverage (${{ matrix.name }})
         uses: codecov/codecov-action@v5
@@ -136,3 +127,27 @@ jobs:
           binary: codecovcli
           working-directory: libs/shared
 
+  # This job works around a strange interaction between reusable workflows and
+  # path filters.
+  #
+  # When a job that uses a reusable workflow is skipped, a single check shows up
+  # for it (e.g. `API CI / Test`). If the job is _not_ skipped, that check does
+  # not appear and instead you see checks for all of the jobs nested in the
+  # reusable workflow (`API CI / Test / Run tests`). There's no single check
+  # that's consistently there which you can mark as required.
+  #
+  # Because this job does not use a reusable workflow, it will produce the same
+  # check whether or not it is skipped. So, we can make this check required and
+  # have it figure out whether the jobs we actually care about failed.
+  shared-required-checks:
+    name: Required checks (Shared)
+    if: ${{ !cancelled() && inputs.skip == false }}
+    runs-on: ubuntu-latest
+    needs: [shared-test, shared-lint]
+    steps:
+      - name: Fail lint
+        if: ${{ needs.shared-lint.result == 'failure' }}
+        run: exit 1
+      - name: Fail tests
+        if: ${{ needs.shared-test.result == 'failure' }}
+        run: exit 1
diff --git a/.github/workflows/worker-ci.yml b/.github/workflows/worker-ci.yml
--- a/.github/workflows/worker-ci.yml
+++ b/.github/workflows/worker-ci.yml
@@ -1,26 +1,11 @@
 name: Worker CI
 
 on:
-  push:
-    tags:
-      - prod-*
-    branches:
-      - main
-      - staging
-    paths:
-      - 'apps/worker/**'
-      - 'apps/worker'
-      - 'libs/**'
-  pull_request:
-    paths:
-      - 'apps/worker/**'
-      - 'apps/worker'
-      - 'libs/**'
-  merge_group:
-    paths:
-      - 'apps/worker/**'
-      - 'apps/worker'
-      - 'libs/**'
+  workflow_call:
+    inputs: 
+      skip:
+        type: boolean
+        default: false
 
 permissions:
   contents: "read"
@@ -28,25 +13,24 @@ permissions:
   issues: "write"
   pull-requests: "write"
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
-  cancel-in-progress: true
-
 jobs:
   worker-lint:
     name: Run Lint (Worker)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/lint.yml@v1.2.31
     with:
       working_directory: apps/worker
 
   worker-mypy:
     name: Patch typing (Worker)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/mypy.yml@v1.2.31
     with:
       working_directory: apps/worker
 
   worker-build:
     name: Build App (Worker)
+    if: ${{ inputs.skip == false }}
     uses: codecov/gha-workflows/.github/workflows/build-app.yml@v1.2.31
     secrets: inherit
     with:
@@ -56,6 +40,7 @@ jobs:
   # Runs create-commit, create-report
   worker-codecovstartup:
     name: Codecov Startup (Worker)
+    if: ${{ inputs.skip == false }}
     needs: worker-build
     uses: codecov/gha-workflows/.github/workflows/codecov-startup.yml@v1.2.31
     secrets: inherit
@@ -64,8 +49,9 @@ jobs:
 
   worker-test:
     name: Test (Worker)
+    if: ${{ inputs.skip == false }}
     needs: [worker-build, worker-codecovstartup]
-    uses: codecov/gha-workflows/.github/workflows/run-tests.yml@v1.2.31
+    uses: codecov/gha-workflows/.github/workflows/run-tests.yml@pr45
     secrets: inherit
     with:
       repo: ${{ vars.CODECOV_WORKER_IMAGE_V2 || 'codecov/self-hosted-worker' }}
@@ -74,6 +60,7 @@ jobs:
 
   worker-build-self-hosted:
     name: Build Self Hosted (Worker)
+    if: ${{ inputs.skip == false }}
     needs: [worker-build, worker-test]
     uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.31
     secrets: inherit
@@ -84,7 +71,7 @@ jobs:
   worker-staging:
     name: Push Staging Image (Worker)
     needs: [worker-build, worker-test]
-    if: ${{ github.event_name == 'push' && (github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/staging') && github.repository_owner == 'codecov' }}
+    if: ${{ inputs.skip == false && github.event_name == 'push' && (github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/staging') && github.repository_owner == 'codecov' }}
     uses: codecov/gha-workflows/.github/workflows/push-env.yml@v1.2.31
     secrets: inherit
     with:
@@ -96,7 +83,7 @@ jobs:
   worker-production:
     name: Push Production Image (Worker)
     needs: [worker-build, worker-test]
-    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
+    if: ${{ inputs.skip == false && github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
     uses: codecov/gha-workflows/.github/workflows/push-env.yml@v1.2.31
     secrets: inherit
     with:
@@ -109,9 +96,34 @@ jobs:
     name: Push Self Hosted Image (Worker)
     needs: [worker-build-self-hosted, worker-test]
     secrets: inherit
-    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
+    if: ${{ inputs.skip == false && github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'codecov' }}
     uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.31
     with:
       push_rolling: true
       repo: ${{ vars.CODECOV_WORKER_IMAGE_V2 || 'codecov/self-hosted-worker' }}
       working_directory: apps/worker
+
+  # This job works around a strange interaction between reusable workflows and
+  # path filters.
+  #
+  # When a job that uses a reusable workflow is skipped, a single check shows up
+  # for it (e.g. `API CI / Test`). If the job is _not_ skipped, that check does
+  # not appear and instead you see checks for all of the jobs nested in the
+  # reusable workflow (`API CI / Test / Run tests`). There's no single check
+  # that's consistently there which you can mark as required.
+  #
+  # Because this job does not use a reusable workflow, it will produce the same
+  # check whether or not it is skipped. So, we can make this check required and
+  # have it figure out whether the jobs we actually care about failed.
+  worker-required-checks:
+    name: Required checks (Worker)
+    if: ${{ !cancelled() && inputs.skip == false }}
+    runs-on: ubuntu-latest
+    needs: [worker-test, worker-lint]
+    steps:
+      - name: Fail lint
+        if: ${{ needs.worker-lint.result == 'failure' }}
+        run: exit 1
+      - name: Fail tests
+        if: ${{ needs.worker-test.outputs.tests_passed == 'failure' }}
+        run: exit 1
